#!/usr/bin/env python3

from glob import glob
import json

input_filenames = glob("./src/**/*.json", recursive=True)

if __name__ == "__main__":
    with open("./list.txt", "wt") as output_file:
        output_file.write("""! Title: AI uBlock Blacklist
    ! Expires: 1 day
    ! Homepage: https://github.com/alvi-se/ai-ublock-blacklist
    ! THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY

    """)

        for filename in input_filenames:
            output_file.write(f"\n! Reading file {filename}\n")
            with open(filename, "rt") as input_file:
                input_source = json.load(input_file)
            
            for s in input_source["sites"]:
                line = '||%s^$doc,reason="%s"\n' % (s["site"], s["reason"])
                output_file.write(line)

